"""Tests for pdf_extractor.py.

Note: pdfplumber is not required for unit tests — we mock the PDF text extraction.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from crawler.bbc.pdf_extractor import (
    clean_pdf_text,
    extract_text_from_pdf_bytes,
    save_transcript,
)


# Minimal valid PDF (a one-page blank document) — generated by pdfplumber in conftest
SAMPLE_PDF_TEXT = """\
BBC Learning English - 6 Minute English

Should animals be kept in zoos?
8 May 2025

Neil: Hello and welcome to 6 Minute English. I'm Neil.
Sam: And I'm Sam. Today we're discussing zoos.

BBC Learning English
Page 1 of 2
"""


class TestCleanPdfText:
    def test_strips_bbc_boilerplate(self):
        raw = SAMPLE_PDF_TEXT
        cleaned = clean_pdf_text(raw)
        assert "Page 1 of" not in cleaned
        assert "BBC Learning English" not in cleaned.split("\n")[-1]

    def test_normalizes_whitespace(self):
        raw = "Hello\n\n\n\n\nWorld   \n  Again"
        cleaned = clean_pdf_text(raw)
        assert "\n\n\n" not in cleaned
        assert "  " not in cleaned

    def test_removes_header_footer_lines(self):
        raw = "BBC Learning English\nReal content here\nPage 2 of 5"
        cleaned = clean_pdf_text(raw)
        lines = [l for l in cleaned.split("\n") if l.strip()]
        assert "Real content here" in lines
        assert not any(l.startswith("Page ") for l in lines)

    def test_empty_input(self):
        assert clean_pdf_text("") == ""
        assert clean_pdf_text("\n\n\n") == ""


class TestExtractTextFromPdfBytes:
    def test_returns_string(self):
        # Empty bytes — extractor should handle gracefully
        result = extract_text_from_pdf_bytes(b"")
        assert isinstance(result, str)
        assert result == ""

    def test_handles_invalid_pdf(self):
        # Not a real PDF
        result = extract_text_from_pdf_bytes(b"not a pdf")
        assert isinstance(result, str)


class TestSaveTranscript:
    def test_writes_text_file(self, tmp_path: Path):
        target = tmp_path / "transcript.txt"
        save_transcript(SAMPLE_PDF_TEXT, target)
        assert target.exists()
        content = target.read_text(encoding="utf-8")
        assert "Neil" in content
        assert "Sam" in content

    def test_creates_parent_dirs(self, tmp_path: Path):
        target = tmp_path / "nested" / "dir" / "transcript.txt"
        save_transcript("hello", target)
        assert target.exists()

    def test_overwrites_existing(self, tmp_path: Path):
        target = tmp_path / "transcript.txt"
        target.write_text("old content")
        save_transcript("new content", target)
        assert target.read_text(encoding="utf-8") == "new content"
